"""Export promptlink's detection rules for the web checker.

The rules live in one place: promptlink/detector.py. This script converts
them into docs/rules.js so the browser version uses exactly the same
patterns. Python's regex dialect differs slightly from JavaScript's, so
Unicode-aware word boundaries and word characters are translated here.

Run after changing any rule:

    python scripts/export_web_rules.py

tests/test_web_parity.py fails if docs/rules.js is out of date, or if the
JavaScript engine ever disagrees with the Python one.
"""

from __future__ import annotations

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from promptlink import __version__  # noqa: E402
from promptlink import detector  # noqa: E402
from promptlink import page  # noqa: E402

OUT = os.path.join(ROOT, "docs", "rules.js")

WORD = r"\p{L}\p{N}_"
# Python's \b is Unicode-aware; JavaScript's is ASCII-only even with /u.
UNICODE_BOUNDARY = (rf"(?:(?<=[{WORD}])(?![{WORD}])|(?<![{WORD}])(?=[{WORD}]))")


def py_to_js(pattern: str) -> str:
    """Translate the subset of Python regex syntax the rules use."""
    out, i, in_class = [], 0, False
    while i < len(pattern):
        ch = pattern[i]
        if ch == "\\" and i + 1 < len(pattern):
            nxt = pattern[i + 1]
            if nxt == "b" and not in_class:
                out.append(UNICODE_BOUNDARY)
            elif nxt == "w":
                out.append(WORD if in_class else f"[{WORD}]")
            elif nxt == "-" and not in_class:
                out.append("-")          # '\-' is invalid outside a class in /u mode
            elif nxt in " '\"#&%!,:;=@`~<>" :
                out.append(nxt)          # identity escapes JS /u mode rejects
            else:
                out.append(ch + nxt)
            i += 2
            continue
        if ch == "[" and not in_class:
            in_class = True
        elif ch == "]" and in_class:
            in_class = False
        out.append(ch)
        i += 1
    return "".join(out)


def build() -> dict:
    return {
        "version": __version__,
        "assistantHosts": detector.ASSISTANT_HOSTS,
        "pathAssistants": [
            {"host": h, "prefix": p, "required": list(r) if r else None, "name": n}
            for h, p, r, n in detector.PATH_ASSISTANTS
        ],
        "promptParams": list(detector.PROMPT_PARAMS),
        "nestedUrlParams": list(detector.NESTED_URL_PARAMS),
        "zeroWidth": detector.ZERO_WIDTH,
        "summaryRequest": py_to_js(detector.SUMMARY_REQUEST.pattern),
        "rules": [
            {"id": r.id, "category": r.category, "weight": r.weight,
             "description": r.description, "patterns": [py_to_js(p) for p in r.patterns]}
            for r in detector.RULES
        ],
        # Page-content scanner (promptlink/page.py): used by docs/page.js and the extension.
        "page": {
            "address": py_to_js(page.ADDRESS.pattern),
            "instruct": py_to_js(page.INSTRUCT.pattern),
            "quick": py_to_js(page.QUICK.pattern),
            "override": py_to_js(page.PAGE_OVERRIDE.pattern),
            "hiddenWhere": sorted(page.HIDDEN_WHERE),
            "whereText": page.WHERE_TEXT,
            "metaNames": sorted(page.META_NAMES),
            "textAttrs": list(page.TEXT_ATTRS),
            "srClasses": sorted(page.SR_CLASSES),
            # HTML extraction (the crawler's view of a page, for pasted page code)
            "hiddenStyle": [[py_to_js(p.pattern), reason] for p, reason in page.HIDDEN_STYLE],
            "sameColour": [py_to_js(p.pattern) for p in page.SAME_COLOUR],
            "hideClasses": sorted(page.HIDE_CLASSES),
            "skipTags": sorted(page.SKIP_TAGS),
            "voidTags": sorted(page.VOID_TAGS),
            "blockTags": sorted(page.BLOCK_TAGS),
        },
    }


def render() -> str:
    data = json.dumps(build(), indent=1, ensure_ascii=True)
    return (
        "// GENERATED by scripts/export_web_rules.py from promptlink/detector.py.\n"
        "// Do not edit by hand: change the Python rules and re-run the script.\n"
        "(function (g) {\n"
        f"  var RULES = {data};\n"
        "  g.PROMPTLINK_RULES = RULES;\n"
        "  if (typeof module !== 'undefined' && module.exports) module.exports = RULES;\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this);\n"
    )


if __name__ == "__main__":
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(render())
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(detector.RULES)} rules, v{__version__})")
